// <auto-generated />
using System;
using CampusConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusConnect.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223114227_AddProfessorRole")]
    partial class AddProfessorRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusConnect.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("CampusConnect.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00071acf-1d28-4d25-b4ba-dbd1c5cbafe0",
                            CreatedAt = new DateTime(2025, 12, 23, 11, 42, 26, 57, DateTimeKind.Utc).AddTicks(4597),
                            Email = "admin1@unibuc.ro",
                            EmailConfirmed = true,
                            FirstName = "Andrei",
                            LastName = "Popescu",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@UNIBUC.RO",
                            NormalizedUserName = "ADMIN1@UNIBUC.RO",
                            PasswordHash = "AQAAAAIAAYagAAAAEBb6XbXg5/2RHrwTN5RG2WMbwK8uQePgtLEaHnAsi+3GJW6mLNG6Na1yKASZQn42Qg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f6d6524b-3015-4767-9504-1881ebbc81c1",
                            TwoFactorEnabled = false,
                            UserName = "admin1@unibuc.ro"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c4b0ae2-fc7e-4bc5-9a6a-e94379054cf0",
                            CreatedAt = new DateTime(2025, 12, 23, 11, 42, 26, 150, DateTimeKind.Utc).AddTicks(3112),
                            Email = "admin2@unibuc.ro",
                            EmailConfirmed = true,
                            FirstName = "Maria",
                            LastName = "Ionescu",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@UNIBUC.RO",
                            NormalizedUserName = "ADMIN2@UNIBUC.RO",
                            PasswordHash = "AQAAAAIAAYagAAAAEH+Fa3Fu+BzNnPgdJ8QE+r3NRoNom10M3SvB+jvelJOerUidG+qSAQOfid4sKubj3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03df8f16-0e61-4ab5-95c8-23c52b228113",
                            TwoFactorEnabled = false,
                            UserName = "admin2@unibuc.ro"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01051681-cd8c-4a5f-ac78-22cf63cbb108",
                            CreatedAt = new DateTime(2025, 12, 23, 11, 42, 26, 252, DateTimeKind.Utc).AddTicks(6451),
                            Email = "student1@s.unibuc.ro",
                            EmailConfirmed = true,
                            FirstName = "Ion",
                            LastName = "Vasilescu",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@S.UNIBUC.RO",
                            NormalizedUserName = "STUDENT1@S.UNIBUC.RO",
                            PasswordHash = "AQAAAAIAAYagAAAAEF1XfU7/HfqXzCBMZbNfJyN4WtEiI3vFl54SNxiXYi78SjRLrinEn7KIB0AOAfMS8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd2867d4-273f-4cfb-a028-a7821fe513b6",
                            TwoFactorEnabled = false,
                            UserName = "student1@s.unibuc.ro"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5996806f-be40-415e-a669-3e4bcf235b0c",
                            CreatedAt = new DateTime(2025, 12, 23, 11, 42, 26, 349, DateTimeKind.Utc).AddTicks(661),
                            Email = "student2@s.unibuc.ro",
                            EmailConfirmed = true,
                            FirstName = "Elena",
                            LastName = "Georgescu",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT2@S.UNIBUC.RO",
                            NormalizedUserName = "STUDENT2@S.UNIBUC.RO",
                            PasswordHash = "AQAAAAIAAYagAAAAEMfzztcRt9vne6HLSkHKvrDAnqmNwBpb19WILDE4r1osyggbKaQPxnatO6DFutjwNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47e12480-6eb3-41ba-abec-7d38fe7c40bf",
                            TwoFactorEnabled = false,
                            UserName = "student2@s.unibuc.ro"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdad3ea6-6283-4ede-8a3a-5b4ddb2ce6ce",
                            CreatedAt = new DateTime(2025, 12, 23, 11, 42, 26, 452, DateTimeKind.Utc).AddTicks(5162),
                            Email = "anastasia.ispas@s.unibuc.ro",
                            EmailConfirmed = true,
                            FirstName = "Anastasia",
                            LastName = "Ispas",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANASTASIA.ISPAS@S.UNIBUC.RO",
                            NormalizedUserName = "ANASTASIA.ISPAS@S.UNIBUC.RO",
                            PasswordHash = "AQAAAAIAAYagAAAAELMEOysK1MuywsLoctUIcGtEQ41vrj45nR/UPgF9bYbzKLYScSHiTCmBLVTGfyeZSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "36d16e1f-ebfa-47dc-928b-1dc0dff4c86e",
                            TwoFactorEnabled = false,
                            UserName = "anastasia.ispas@s.unibuc.ro"
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e3c3120-8ab9-4da4-a53a-2ce4664d8df3",
                            CreatedAt = new DateTime(2025, 12, 23, 11, 42, 26, 558, DateTimeKind.Utc).AddTicks(3779),
                            Email = "irina-maria.istrate@s.unibuc.ro",
                            EmailConfirmed = true,
                            FirstName = "Irina-Maria",
                            LastName = "Istrate",
                            LockoutEnabled = false,
                            NormalizedEmail = "IRINA-MARIA.ISTRATE@S.UNIBUC.RO",
                            NormalizedUserName = "IRINA-MARIA.ISTRATE@S.UNIBUC.RO",
                            PasswordHash = "AQAAAAIAAYagAAAAEBT4sAIlqRbBocPbS5OVsyH8MyaEmOPzkN0QB928X5Bp9EqlQnTGNPIjGxhWLJkavw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ed1fc2b-c8d9-4e1b-8893-1e919f190048",
                            TwoFactorEnabled = false,
                            UserName = "irina-maria.istrate@s.unibuc.ro"
                        });
                });

            modelBuilder.Entity("CampusConnect.Domain.Entities.EventParticipant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("CampusConnect.Domain.Entities.SavedAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId", "AnnouncementId")
                        .IsUnique();

                    b.ToTable("SavedAnnouncements");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1ac54da4-37c6-464c-95bc-4ac77b718324",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "f16c879f-a48f-44ef-9b6d-44a588fcadd1",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "7078d706-b6e5-4147-a9a0-09e42fad5f98",
                            Name = "Professor",
                            NormalizedName = "PROFESSOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 15,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("CampusConnect.Domain.Entities.EventParticipant", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Domain.Entities.ApplicationUser", "User")
                        .WithMany("EventsJoined")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusConnect.Domain.Entities.SavedAnnouncement", b =>
                {
                    b.HasOne("CampusConnect.Domain.Entities.Announcement", "Announcement")
                        .WithMany()
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.HasOne("CampusConnect.Domain.Entities.ApplicationUser", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CampusConnect.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CampusConnect.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CampusConnect.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampusConnect.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("EventsJoined");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
